# Generated by Django 4.0.2 on 2022-02-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
                ('vendor', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('software_version', models.CharField(max_length=100)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
