# Generated by Django 4.0.2 on 2022-03-05 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.devices')),
            ],
        ),
    ]
