# Generated by Django 4.0.2 on 2022-03-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('vlans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vlan',
            new_name='Vlans',
        ),
    ]
