# Generated by Django 4.0.2 on 2022-05-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlans', '0003_remove_vlans_ip_address_vlans_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlans',
            name='exists_on_device',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
