# Generated by Django 4.0.2 on 2022-05-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlans', '0004_vlans_exists_on_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlans',
            name='exists_on_device',
        ),
    ]
